In [106]:
pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [107]:
import pandas as pd

In [108]:
pd.__version__

'3.0.6'

In [109]:
a = pd.Series([1,2,3,4,5,6,7,8])
a.sort_values()

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

## start 5

In [110]:
a.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

## last five

In [111]:
a.tail()

3    4
4    5
5    6
6    7
7    8
dtype: int64

## to find count of data

In [112]:
a.count()

np.int64(8)

## to find null

In [113]:
a.notnull()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
dtype: bool

## find null

In [114]:
b = pd.Series([1,None,2,3])
b.isnull()

0    False
1     True
2    False
3    False
dtype: bool

## fill the missing values

In [115]:
b = b.fillna(0)
b

0    1.0
1    0.0
2    2.0
3    3.0
dtype: float64

In [116]:
b

0    1.0
1    0.0
2    2.0
3    3.0
dtype: float64

## data frame

In [117]:
frame = pd.DataFrame({
    "name":["kartikey","tyagi ji"],
    "age":[21,22]
})
frame

       name  age
0  kartikey   21
1  tyagi ji   22

In [118]:
v = pd.Series([40,2,10])
b = pd.Series([40,5,12])
n = pd.DataFrame({
    "cq":v,
    "cw":b
})
n

   cq  cw
0  40  40
1   2   5
2  10  12

In [119]:
n.dtypes

cq    int64
cw    int64
dtype: object

In [120]:
n.loc[1]

cq    2
cw    5
Name: 1, dtype: int64

## iloc work on the index

In [121]:
n.iloc[1,0]

np.int64(2)

In [122]:
# print(n[n["cq" == 40 ] < 2])

In [123]:
n["new col"] = [1,2,3,]
n

   cq  cw  new col
0  40  40        1
1   2   5        2
2  10  12        3

In [124]:
del n["new col"]

In [125]:
n

   cq  cw
0  40  40
1   2   5
2  10  12

In [126]:
# n = n.drop(columns=["cq"])

In [127]:
n

   cq  cw
0  40  40
1   2   5
2  10  12

In [128]:
n.loc[n['cw'] == 4] =10
n

   cq  cw
0  40  40
1   2   5
2  10  12

## indexing and selection

In [129]:
u = pd.DataFrame({
    "age":[1,2,3,4,5,6],
    "value":[10,20,30,40,50,60]
})
u

   age  value
0    1     10
1    2     20
2    3     30
3    4     40
4    5     50
5    6     60

In [130]:
u["sector"] = [1,2,3,4,5,6]
u

   age  value  sector
0    1     10       1
1    2     20       2
2    3     30       3
3    4     40       4
4    5     50       5
5    6     60       6

In [131]:
u.set_index("sector",inplace=True)
u

        age  value
sector
1         1     10
2         2     20
3         3     30
4         4     40
5         5     50
6         6     60

In [132]:
u.loc[1,"value"]

np.int64(10)

## multi data index

In [133]:
multi_data = pd.DataFrame({
    "marks":[100,200,300,400],
    "roll_number":[1,2,3,4],
    "name":["kt","bt","ct","et"]
}).set_index(["marks","roll_number"])
multi_data

                  name
marks roll_number
100   1             kt
200   2             bt
300   3             ct
400   4             et


## filtering data

In [134]:
multi_data[multi_data["name"] == "kt"]

                  name
marks roll_number
100   1             kt

## filtering index

In [135]:
multi_data.query('marks == 300')

                  name
marks roll_number
300   3             ct

## Working with data

In [136]:
multi_data.to_csv("class_report.csv")

In [137]:
class_report_csv = pd.read_csv("class_report.csv")
print(class_report_csv)

   marks  roll_number name
0    100            1   kt
1    200            2   bt
2    300            3   ct
3    400            4   et

In [138]:
import numpy as np
dictt = {'x':[1,2,3],"y":np.array([1,2,3]),"z":22}
dictt

{'x': [1, 2, 3], 'y': array([1, 2, 3]), 'z': 22}

In [139]:
pd.DataFrame(dictt)

   x  y   z
0  1  1  22
1  2  2  22
2  3  3  22

In [140]:
listing = [[1,2,3],[1,2,3],[5,5,5]]
pd.DataFrame(listing,columns=['x','y','z'])

   x  y  z
0  1  2  3
1  1  2  3
2  5  5  5

In [141]:
narr = np.array([
    [1,2,3],
    [1,2,4],
    [1,5,6]
])
pd.DataFrame(narr,columns=("x","y","z"))

   x  y  z
0  1  2  3
1  1  2  4
2  1  5  6

## Data cleaning and preprocesing

In [142]:
sales = pd.Series([1,None,5,5])
sales

0    1.0
1    NaN
2    5.0
3    5.0
dtype: float64

In [143]:
sales.dropna()

0    1.0
2    5.0
3    5.0
dtype: float64

In [144]:
sales.fillna(5,inplace=True)

0    1.0
1    5.0
2    5.0
3    5.0
dtype: float64

In [145]:
sales.fillna(sales.mean(),inplace=True)

0    1.0
1    5.0
2    5.0
3    5.0
dtype: float64

In [146]:
sales.drop_duplicates()

0    1.0
1    5.0
dtype: float64

In [147]:
sales.replace(5,100,inplace=True)

0      1.0
1    100.0
2    100.0
3    100.0
dtype: float64

In [148]:
sales

0      1.0
1    100.0
2    100.0
3    100.0
dtype: float64

In [149]:
sales = sales.astype(int)
sales

0      1
1    100
2    100
3    100
dtype: int64

In [150]:
sales["a2"] = [1,2,4,9]
sales

0                1
1              100
2              100
3              100
a2    [1, 2, 4, 9]
dtype: object

## Data Aggregation and Grouping

In [151]:
s1 = pd.Series(data=['a','b','a','b','c','c'])
s2 = pd.Series(data=[1,2,1,2,5,5])
data = pd.DataFrame({
    "name":s1,
    "lemonades":s2
})
data

  name  lemonades
0    a          1
1    b          2
2    a          1
3    b          2
4    c          5
5    c          5

In [152]:
dataGroup = data.groupby("name")
dataGroup.sum()

      lemonades
name
a             2
b             4
c            10

In [153]:
dataGroup["lemonades"].mean()

name
a    1.0
b    2.0
c    5.0
Name: lemonades, dtype: float64

In [154]:
dataGroup["lemonades"].max()

name
a    1
b    2
c    5
Name: lemonades, dtype: int64

In [155]:
## by Default pivot table give average ... can use aggfunc for other aggregration

In [156]:
data.pivot_table(values="lemonades",index="name")

      lemonades
name
a           1.0
b           2.0
c           5.0

In [157]:
## cross tabs
pd.crosstab(data['name'],data['lemonades'])

lemonades  1  2  5
name
a          2  0  0
b          0  2  0
c          0  0  2

## Merging Joining and Concatination

In [161]:
s1 = pd.Series(data=['a','b','a','b','c'])
s2 = pd.Series(data=[1,2,1,2,5])
data1 = pd.DataFrame({
    "name":s1,
    "lemonades":s2
})

s1 = pd.Series(data=['a','a','a','b','c'])
s2 = pd.Series(data=[10,20,10,20,50])
data2 = pd.DataFrame({
    "name":s1,
    "lemon":s2
})

In [162]:
pd.concat([data1,data2])

  name  lemonades  lemon
0    a        1.0    NaN
1    b        2.0    NaN
2    a        1.0    NaN
3    b        2.0    NaN
4    c        5.0    NaN
0    a        NaN   10.0
1    a        NaN   20.0
2    a        NaN   10.0
3    b        NaN   20.0
4    c        NaN   50.0

In [163]:
pd.merge(data1,data2,on='name')

  name  lemonades  lemon
0    a          1     10
1    a          1     20
2    a          1     10
3    b          2     20
4    a          1     10
5    a          1     20
6    a          1     10
7    b          2     20
8    c          5     50

In [164]:
data1.join(data2.set_index('name'), on='name')

  name  lemonades  lemon
0    a          1     10
0    a          1     20
0    a          1     10
1    b          2     20
2    a          1     10
2    a          1     20
2    a          1     10
3    b          2     20
4    c          5     50

## working with time Series

In [173]:
df = pd.read_csv("~/Downloads/customer_data.csv")

df

    index        date    customer_name  count        city order_status  amount
0       1  2026-10-11      Sneha Joshi      1       Noida      Pending    2206
1       2  2026-09-15   Arjun Malhotra     24       Delhi    Cancelled    4667
2       3  2026-09-06       Ritika Sen     14       Delhi    Completed     967
3       4  2026-09-14     Karan Bansal     17      Jaipur    Completed    4797
4       5  2026-09-13  Abhishek Tiwari     14     Panipat      Pending    2478
5       6  2026-09-01      Aditya Jain     23    Gurugram      Pending    2476
6       7  2026-09-10     Pooja Mishra     25  Chandigarh    Completed     959
7       8  2026-09-25      Rohan Kumar     12  Chandigarh    Cancelled    2366
8       9  2026-09-03      Divya Menon     18       Delhi      Pending     845
9      10  2026-10-06      Sahil Arora     21      Jaipur      Pending    4929
10     11  2026-09-13     Vikram Patel      2       Noida    Completed    2570
11     12  2026-09-06     Karan Bansal      4    Gurugram      Pending    3914
12     13  2026-10-11     Aditi Saxena      6  Chandigarh      Pending    1916
13     14  2026-10-13       Meera Nair     23       Noida    Cancelled     784
14     15  2026-10-09      Aditya Jain     18       Noida    Completed    1538
15     16  2026-09-30    Mohit Agarwal      9       Noida    Cancelled    4762
16     17  2026-09-15      Varun Sethi     25       Delhi    Completed     462
17     18  2026-09-21      Shreya Iyer      9       Delhi    Completed    4846
18     19  2026-10-16      Varun Sethi      7       Noida      Pending    3441
19     20  2026-10-12      Divya Menon      5  Chandigarh    Completed    2220
20     21  2026-10-06  Abhishek Tiwari      9       Noida    Cancelled    3709
21     22  2026-10-08      Shreya Iyer     12     Panipat    Completed    4374
22     23  2026-10-02     Ananya Mehta     25       Delhi    Completed    1452
23     24  2026-10-11      Aditya Jain     22    Gurugram    Cancelled     720
24     25  2026-09-25    Mohit Agarwal     20    Gurugram    Cancelled    2259
25     26  2026-10-06     Aarav Sharma     22       Noida    Completed    4598
26     27  2026-09-18       Tanya Bose      4  Chandigarh      Pending    1495
27     28  2026-09-30     Aarav Sharma     24       Noida      Pending    4300
28     29  2026-09-12      Saurabh Roy      4       Noida      Pending    4358
29     30  2026-10-09     Manish Yadav      5  Chandigarh    Completed    4618
30     31  2026-10-04     Aarav Sharma     20  Chandigarh      Pending     359
31     32  2026-09-08     Aditi Saxena     10     Panipat    Completed    2173
32     33  2026-10-07     Ananya Mehta      3       Noida      Pending     766
33     34  2026-10-05   Arjun Malhotra      5       Noida      Pending    4703
34     35  2026-09-11       Nikhil Das     17      Jaipur      Pending    1935
35     36  2026-10-05     Manish Yadav     23  Chandigarh      Pending    3259
36     37  2026-09-29      Muskan Gill     15       Delhi    Completed    2040
37     38  2026-09-05       Tanya Bose      1      Jaipur    Cancelled    2085
38     39  2026-10-08     Karan Bansal      1       Delhi    Cancelled     682
39     40  2026-09-15     Vikram Patel      2  Chandigarh    Completed    4411
40     41  2026-09-16       Meera Nair     22    Gurugram    Completed    4617
41     42  2026-09-09    Gaurav Chopra     19    Gurugram    Completed    4074
42     43  2026-09-27     Manish Yadav      4       Delhi    Cancelled    3731
43     44  2026-09-23     Naina Khanna     14    Gurugram    Cancelled     643
44     45  2026-10-14      Rohan Kumar      2    Gurugram    Cancelled    2979

In [181]:
df

          date    customer_name  count        city order_status  amount
0   2026-10-11      Sneha Joshi      1       Noida      Pending    2206
1   2026-09-15   Arjun Malhotra     24       Delhi    Cancelled    4667
2   2026-09-06       Ritika Sen     14       Delhi    Completed     967
3   2026-09-14     Karan Bansal     17      Jaipur    Completed    4797
4   2026-09-13  Abhishek Tiwari     14     Panipat      Pending    2478
5   2026-09-01      Aditya Jain     23    Gurugram      Pending    2476
6   2026-09-10     Pooja Mishra     25  Chandigarh    Completed     959
7   2026-09-25      Rohan Kumar     12  Chandigarh    Cancelled    2366
8   2026-09-03      Divya Menon     18       Delhi      Pending     845
9   2026-10-06      Sahil Arora     21      Jaipur      Pending    4929
10  2026-09-13     Vikram Patel      2       Noida    Completed    2570
11  2026-09-06     Karan Bansal      4    Gurugram      Pending    3914
12  2026-10-11     Aditi Saxena      6  Chandigarh      Pending    1916
13  2026-10-13       Meera Nair     23       Noida    Cancelled     784
14  2026-10-09      Aditya Jain     18       Noida    Completed    1538
15  2026-09-30    Mohit Agarwal      9       Noida    Cancelled    4762
16  2026-09-15      Varun Sethi     25       Delhi    Completed     462
17  2026-09-21      Shreya Iyer      9       Delhi    Completed    4846
18  2026-10-16      Varun Sethi      7       Noida      Pending    3441
19  2026-10-12      Divya Menon      5  Chandigarh    Completed    2220
20  2026-10-06  Abhishek Tiwari      9       Noida    Cancelled    3709
21  2026-10-08      Shreya Iyer     12     Panipat    Completed    4374
22  2026-10-02     Ananya Mehta     25       Delhi    Completed    1452
23  2026-10-11      Aditya Jain     22    Gurugram    Cancelled     720
24  2026-09-25    Mohit Agarwal     20    Gurugram    Cancelled    2259
25  2026-10-06     Aarav Sharma     22       Noida    Completed    4598
26  2026-09-18       Tanya Bose      4  Chandigarh      Pending    1495
27  2026-09-30     Aarav Sharma     24       Noida      Pending    4300
28  2026-09-12      Saurabh Roy      4       Noida      Pending    4358
29  2026-10-09     Manish Yadav      5  Chandigarh    Completed    4618
30  2026-10-04     Aarav Sharma     20  Chandigarh      Pending     359
31  2026-09-08     Aditi Saxena     10     Panipat    Completed    2173
32  2026-10-07     Ananya Mehta      3       Noida      Pending     766
33  2026-10-05   Arjun Malhotra      5       Noida      Pending    4703
34  2026-09-11       Nikhil Das     17      Jaipur      Pending    1935
35  2026-10-05     Manish Yadav     23  Chandigarh      Pending    3259
36  2026-09-29      Muskan Gill     15       Delhi    Completed    2040
37  2026-09-05       Tanya Bose      1      Jaipur    Cancelled    2085
38  2026-10-08     Karan Bansal      1       Delhi    Cancelled     682
39  2026-09-15     Vikram Patel      2  Chandigarh    Completed    4411
40  2026-09-16       Meera Nair     22    Gurugram    Completed    4617
41  2026-09-09    Gaurav Chopra     19    Gurugram    Completed    4074
42  2026-09-27     Manish Yadav      4       Delhi    Cancelled    3731
43  2026-09-23     Naina Khanna     14    Gurugram    Cancelled     643
44  2026-10-14      Rohan Kumar      2    Gurugram    Cancelled    2979

In [182]:
print(df.columns.tolist())

['date', 'customer_name', 'count', 'city', 'order_status', 'amount']

In [184]:
df['date'] = pd.to_datetime(df['date'])
df

         date    customer_name  count        city order_status  amount
0  2026-10-11      Sneha Joshi      1       Noida      Pending    2206
1  2026-09-15   Arjun Malhotra     24       Delhi    Cancelled    4667
2  2026-09-06       Ritika Sen     14       Delhi    Completed     967
3  2026-09-14     Karan Bansal     17      Jaipur    Completed    4797
4  2026-09-13  Abhishek Tiwari     14     Panipat      Pending    2478
5  2026-09-01      Aditya Jain     23    Gurugram      Pending    2476
6  2026-09-10     Pooja Mishra     25  Chandigarh    Completed     959
7  2026-09-25      Rohan Kumar     12  Chandigarh    Cancelled    2366
8  2026-09-03      Divya Menon     18       Delhi      Pending     845
9  2026-10-06      Sahil Arora     21      Jaipur      Pending    4929
10 2026-09-13     Vikram Patel      2       Noida    Completed    2570
11 2026-09-06     Karan Bansal      4    Gurugram      Pending    3914
12 2026-10-11     Aditi Saxena      6  Chandigarh      Pending    1916
13 2026-10-13       Meera Nair     23       Noida    Cancelled     784
14 2026-10-09      Aditya Jain     18       Noida    Completed    1538
15 2026-09-30    Mohit Agarwal      9       Noida    Cancelled    4762
16 2026-09-15      Varun Sethi     25       Delhi    Completed     462
17 2026-09-21      Shreya Iyer      9       Delhi    Completed    4846
18 2026-10-16      Varun Sethi      7       Noida      Pending    3441
19 2026-10-12      Divya Menon      5  Chandigarh    Completed    2220
20 2026-10-06  Abhishek Tiwari      9       Noida    Cancelled    3709
21 2026-10-08      Shreya Iyer     12     Panipat    Completed    4374
22 2026-10-02     Ananya Mehta     25       Delhi    Completed    1452
23 2026-10-11      Aditya Jain     22    Gurugram    Cancelled     720
24 2026-09-25    Mohit Agarwal     20    Gurugram    Cancelled    2259
25 2026-10-06     Aarav Sharma     22       Noida    Completed    4598
26 2026-09-18       Tanya Bose      4  Chandigarh      Pending    1495
27 2026-09-30     Aarav Sharma     24       Noida      Pending    4300
28 2026-09-12      Saurabh Roy      4       Noida      Pending    4358
29 2026-10-09     Manish Yadav      5  Chandigarh    Completed    4618
30 2026-10-04     Aarav Sharma     20  Chandigarh      Pending     359
31 2026-09-08     Aditi Saxena     10     Panipat    Completed    2173
32 2026-10-07     Ananya Mehta      3       Noida      Pending     766
33 2026-10-05   Arjun Malhotra      5       Noida      Pending    4703
34 2026-09-11       Nikhil Das     17      Jaipur      Pending    1935
35 2026-10-05     Manish Yadav     23  Chandigarh      Pending    3259
36 2026-09-29      Muskan Gill     15       Delhi    Completed    2040
37 2026-09-05       Tanya Bose      1      Jaipur    Cancelled    2085
38 2026-10-08     Karan Bansal      1       Delhi    Cancelled     682
39 2026-09-15     Vikram Patel      2  Chandigarh    Completed    4411
40 2026-09-16       Meera Nair     22    Gurugram    Completed    4617
41 2026-09-09    Gaurav Chopra     19    Gurugram    Completed    4074
42 2026-09-27     Manish Yadav      4       Delhi    Cancelled    3731
43 2026-09-23     Naina Khanna     14    Gurugram    Cancelled     643
44 2026-10-14      Rohan Kumar      2    Gurugram    Cancelled    2979

In [185]:
df.set_index('date',inplace=True)

In [186]:
df

              customer_name  count        city order_status  amount
date
2026-10-11      Sneha Joshi      1       Noida      Pending    2206
2026-09-15   Arjun Malhotra     24       Delhi    Cancelled    4667
2026-09-06       Ritika Sen     14       Delhi    Completed     967
2026-09-14     Karan Bansal     17      Jaipur    Completed    4797
2026-09-13  Abhishek Tiwari     14     Panipat      Pending    2478
2026-09-01      Aditya Jain     23    Gurugram      Pending    2476
2026-09-10     Pooja Mishra     25  Chandigarh    Completed     959
2026-09-25      Rohan Kumar     12  Chandigarh    Cancelled    2366
2026-09-03      Divya Menon     18       Delhi      Pending     845
2026-10-06      Sahil Arora     21      Jaipur      Pending    4929
2026-09-13     Vikram Patel      2       Noida    Completed    2570
2026-09-06     Karan Bansal      4    Gurugram      Pending    3914
2026-10-11     Aditi Saxena      6  Chandigarh      Pending    1916
2026-10-13       Meera Nair     23       Noida    Cancelled     784
2026-10-09      Aditya Jain     18       Noida    Completed    1538
2026-09-30    Mohit Agarwal      9       Noida    Cancelled    4762
2026-09-15      Varun Sethi     25       Delhi    Completed     462
2026-09-21      Shreya Iyer      9       Delhi    Completed    4846
2026-10-16      Varun Sethi      7       Noida      Pending    3441
2026-10-12      Divya Menon      5  Chandigarh    Completed    2220
2026-10-06  Abhishek Tiwari      9       Noida    Cancelled    3709
2026-10-08      Shreya Iyer     12     Panipat    Completed    4374
2026-10-02     Ananya Mehta     25       Delhi    Completed    1452
2026-10-11      Aditya Jain     22    Gurugram    Cancelled     720
2026-09-25    Mohit Agarwal     20    Gurugram    Cancelled    2259
2026-10-06     Aarav Sharma     22       Noida    Completed    4598
2026-09-18       Tanya Bose      4  Chandigarh      Pending    1495
2026-09-30     Aarav Sharma     24       Noida      Pending    4300
2026-09-12      Saurabh Roy      4       Noida      Pending    4358
2026-10-09     Manish Yadav      5  Chandigarh    Completed    4618
2026-10-04     Aarav Sharma     20  Chandigarh      Pending     359
2026-09-08     Aditi Saxena     10     Panipat    Completed    2173
2026-10-07     Ananya Mehta      3       Noida      Pending     766
2026-10-05   Arjun Malhotra      5       Noida      Pending    4703
2026-09-11       Nikhil Das     17      Jaipur      Pending    1935
2026-10-05     Manish Yadav     23  Chandigarh      Pending    3259
2026-09-29      Muskan Gill     15       Delhi    Completed    2040
2026-09-05       Tanya Bose      1      Jaipur    Cancelled    2085
2026-10-08     Karan Bansal      1       Delhi    Cancelled     682
2026-09-15     Vikram Patel      2  Chandigarh    Completed    4411
2026-09-16       Meera Nair     22    Gurugram    Completed    4617
2026-09-09    Gaurav Chopra     19    Gurugram    Completed    4074
2026-09-27     Manish Yadav      4       Delhi    Cancelled    3731
2026-09-23     Naina Khanna     14    Gurugram    Cancelled     643
2026-10-14      Rohan Kumar      2    Gurugram    Cancelled    2979

In [188]:
## converting Strings to date
pd.to_datetime('2026-10-14')

Timestamp('2026-10-14 00:00:00')

In [192]:
df.resample('ME').sum()
## month start (MS)

,customer_name,count,city,order_status,amount
date,,,,,
2026-09-30,Aditya JainDivya MenonTanya BoseRitika SenKara...,352,GurugramDelhiJaipurDelhiGurugramPanipatGurugra...,PendingPendingCancelledCompletedPendingComplet...,74230
2026-10-31,Ananya MehtaAarav SharmaArjun MalhotraManish Y...,230,DelhiChandigarhNoidaChandigarhJaipurNoidaNoida...,CompletedPendingPendingPendingPendingCancelled...,49253

In [195]:
df.resample('MS').sum()

,customer_name,count,city,order_status,amount
date,,,,,
2026-09-01,Aditya JainDivya MenonTanya BoseRitika SenKara...,352,GurugramDelhiJaipurDelhiGurugramPanipatGurugra...,PendingPendingCancelledCompletedPendingComplet...,74230
2026-10-01,Ananya MehtaAarav SharmaArjun MalhotraManish Y...,230,DelhiChandigarhNoidaChandigarhJaipurNoidaNoida...,CompletedPendingPendingPendingPendingCancelled...,49253

In [196]:
## annualy

In [199]:
df.resample('YE').sum()

,customer_name,count,city,order_status,amount
date,,,,,
2026-12-31,Aditya JainDivya MenonTanya BoseRitika SenKara...,582,GurugramDelhiJaipurDelhiGurugramPanipatGurugra...,PendingPendingCancelledCompletedPendingComplet...,123483

In [201]:
## shifting and lagging 
df['Previous count'] = df['count'].shift(1)

In [202]:
df

,customer_name,count,city,order_status,amount,Previous count
date,,,,,,
2026-10-11,Sneha Joshi,1,Noida,Pending,2206,NaN
2026-09-15,Arjun Malhotra,24,Delhi,Cancelled,4667,1.0
2026-09-06,Ritika Sen,14,Delhi,Completed,967,24.0
2026-09-14,Karan Bansal,17,Jaipur,Completed,4797,14.0
2026-09-13,Abhishek Tiwari,14,Panipat,Pending,2478,17.0
2026-09-01,Aditya Jain,23,Gurugram,Pending,2476,14.0
2026-09-10,Pooja Mishra,25,Chandigarh,Completed,959,23.0
2026-09-25,Rohan Kumar,12,Chandigarh,Cancelled,2366,25.0
2026-09-03,Divya Menon,18,Delhi,Pending,845,12.0
2026-10-06,Sahil Arora,21,Jaipur,Pending,4929,18.0
2026-09-13,Vikram Patel,2,Noida,Completed,2570,21.0
2026-09-06,Karan Bansal,4,Gurugram,Pending,3914,2.0
2026-10-11,Aditi Saxena,6,Chandigarh,Pending,1916,4.0
2026-10-13,Meera Nair,23,Noida,Cancelled,784,6.0
2026-10-09,Aditya Jain,18,Noida,Completed,1538,23.0
2026-09-30,Mohit Agarwal,9,Noida,Cancelled,4762,18.0
2026-09-15,Varun Sethi,25,Delhi,Completed,462,9.0
2026-09-21,Shreya Iyer,9,Delhi,Completed,4846,25.0
2026-10-16,Varun Sethi,7,Noida,Pending,3441,9.0
2026-10-12,Divya Menon,5,Chandigarh,Completed,2220,7.0
2026-10-06,Abhishek Tiwari,9,Noida,Cancelled,3709,5.0
2026-10-08,Shreya Iyer,12,Panipat,Completed,4374,9.0
2026-10-02,Ananya Mehta,25,Delhi,Completed,1452,12.0
2026-10-11,Aditya Jain,22,Gurugram,Cancelled,720,25.0
2026-09-25,Mohit Agarwal,20,Gurugram,Cancelled,2259,22.0
2026-10-06,Aarav Sharma,22,Noida,Completed,4598,20.0
2026-09-18,Tanya Bose,4,Chandigarh,Pending,1495,22.0
2026-09-30,Aarav Sharma,24,Noida,Pending,4300,4.0
2026-09-12,Saurabh Roy,4,Noida,Pending,4358,24.0
2026-10-09,Manish Yadav,5,Chandigarh,Completed,4618,4.0
2026-10-04,Aarav Sharma,20,Chandigarh,Pending,359,5.0
2026-09-08,Aditi Saxena,10,Panipat,Completed,2173,20.0
2026-10-07,Ananya Mehta,3,Noida,Pending,766,10.0
2026-10-05,Arjun Malhotra,5,Noida,Pending,4703,3.0
2026-09-11,Nikhil Das,17,Jaipur,Pending,1935,5.0
2026-10-05,Manish Yadav,23,Chandigarh,Pending,3259,17.0
2026-09-29,Muskan Gill,15,Delhi,Completed,2040,23.0
2026-09-05,Tanya Bose,1,Jaipur,Cancelled,2085,15.0
2026-10-08,Karan Bansal,1,Delhi,Cancelled,682,1.0
2026-09-15,Vikram Patel,2,Chandigarh,Completed,4411,1.0
2026-09-16,Meera Nair,22,Gurugram,Completed,4617,2.0
2026-09-09,Gaurav Chopra,19,Gurugram,Completed,4074,22.0
2026-09-27,Manish Yadav,4,Delhi,Cancelled,3731,19.0
2026-09-23,Naina Khanna,14,Gurugram,Cancelled,643,4.0
2026-10-14,Rohan Kumar,2,Gurugram,Cancelled,2979,14.0

In [204]:
## rolling average
df['previous rolling'] = df['count'].rolling(window=2).mean()

In [205]:
df

,customer_name,count,city,order_status,amount,Previous count,previous rolling
date,,,,,,,
2026-10-11,Sneha Joshi,1,Noida,Pending,2206,NaN,NaN
2026-09-15,Arjun Malhotra,24,Delhi,Cancelled,4667,1.0,12.5
2026-09-06,Ritika Sen,14,Delhi,Completed,967,24.0,19.0
2026-09-14,Karan Bansal,17,Jaipur,Completed,4797,14.0,15.5
2026-09-13,Abhishek Tiwari,14,Panipat,Pending,2478,17.0,15.5
2026-09-01,Aditya Jain,23,Gurugram,Pending,2476,14.0,18.5
2026-09-10,Pooja Mishra,25,Chandigarh,Completed,959,23.0,24.0
2026-09-25,Rohan Kumar,12,Chandigarh,Cancelled,2366,25.0,18.5
2026-09-03,Divya Menon,18,Delhi,Pending,845,12.0,15.0
2026-10-06,Sahil Arora,21,Jaipur,Pending,4929,18.0,19.5
2026-09-13,Vikram Patel,2,Noida,Completed,2570,21.0,11.5
2026-09-06,Karan Bansal,4,Gurugram,Pending,3914,2.0,3.0
2026-10-11,Aditi Saxena,6,Chandigarh,Pending,1916,4.0,5.0
2026-10-13,Meera Nair,23,Noida,Cancelled,784,6.0,14.5
2026-10-09,Aditya Jain,18,Noida,Completed,1538,23.0,20.5
2026-09-30,Mohit Agarwal,9,Noida,Cancelled,4762,18.0,13.5
2026-09-15,Varun Sethi,25,Delhi,Completed,462,9.0,17.0
2026-09-21,Shreya Iyer,9,Delhi,Completed,4846,25.0,17.0
2026-10-16,Varun Sethi,7,Noida,Pending,3441,9.0,8.0
2026-10-12,Divya Menon,5,Chandigarh,Completed,2220,7.0,6.0
2026-10-06,Abhishek Tiwari,9,Noida,Cancelled,3709,5.0,7.0
2026-10-08,Shreya Iyer,12,Panipat,Completed,4374,9.0,10.5
2026-10-02,Ananya Mehta,25,Delhi,Completed,1452,12.0,18.5
2026-10-11,Aditya Jain,22,Gurugram,Cancelled,720,25.0,23.5
2026-09-25,Mohit Agarwal,20,Gurugram,Cancelled,2259,22.0,21.0
2026-10-06,Aarav Sharma,22,Noida,Completed,4598,20.0,21.0
2026-09-18,Tanya Bose,4,Chandigarh,Pending,1495,22.0,13.0
2026-09-30,Aarav Sharma,24,Noida,Pending,4300,4.0,14.0
2026-09-12,Saurabh Roy,4,Noida,Pending,4358,24.0,14.0
2026-10-09,Manish Yadav,5,Chandigarh,Completed,4618,4.0,4.5
2026-10-04,Aarav Sharma,20,Chandigarh,Pending,359,5.0,12.5
2026-09-08,Aditi Saxena,10,Panipat,Completed,2173,20.0,15.0
2026-10-07,Ananya Mehta,3,Noida,Pending,766,10.0,6.5
2026-10-05,Arjun Malhotra,5,Noida,Pending,4703,3.0,4.0
2026-09-11,Nikhil Das,17,Jaipur,Pending,1935,5.0,11.0
2026-10-05,Manish Yadav,23,Chandigarh,Pending,3259,17.0,20.0
2026-09-29,Muskan Gill,15,Delhi,Completed,2040,23.0,19.0
2026-09-05,Tanya Bose,1,Jaipur,Cancelled,2085,15.0,8.0
2026-10-08,Karan Bansal,1,Delhi,Cancelled,682,1.0,1.0
2026-09-15,Vikram Patel,2,Chandigarh,Completed,4411,1.0,1.5
2026-09-16,Meera Nair,22,Gurugram,Completed,4617,2.0,12.0
2026-09-09,Gaurav Chopra,19,Gurugram,Completed,4074,22.0,20.5
2026-09-27,Manish Yadav,4,Delhi,Cancelled,3731,19.0,11.5
2026-09-23,Naina Khanna,14,Gurugram,Cancelled,643,4.0,9.0
2026-10-14,Rohan Kumar,2,Gurugram,Cancelled,2979,14.0,8.0